"""
documents.py: This file provides methods that can be used to generate natural language summaries for theorems using an LLM and cached metadata.
"""

import json
import os
import math
import tomllib
import zlib
import re
import nltk


from tqdm import tqdm
from nltk.corpus import stopwords

from src.llm import get_document_llm, document_model_name


cached_metadata = {}


# This method returns the metadata (i.e. title, abstract, authors, keywords, etc.) for a given entry
# from a local copy of the Archive of Formal Proofs (configured in config["afp_folder"]).
# Additionally this method caches loaded entires in the 'cached_metadata' dict.
def get_entry_metadata(entry, config):
    metadata_folder = config["components"]["afp"]["local_folder"] + "/metadata/"
    entry_toml = metadata_folder + "entries/" + entry + ".toml"

    if entry in cached_metadata:
        return cached_metadata[entry]

    if os.path.isfile(entry_toml):
        try:
            with open(entry_toml, "rb") as f:
                toml = tomllib.load(f)
                cached_metadata[entry] = {
                    "title": toml.get("title", ""),
                    "abstract": toml.get("abstract", ""),
                }
                return cached_metadata[entry]
        except Exception:
            print("Failed loading file " + entry_toml + ".")
            cached_metadata[entry] = {"title": "", "abstract": ""}
            return cached_metadata[entry]
    else:
        print(f"No metadata file exists at path {entry_toml} for entry {entry}.")
        cached_metadata[entry] = {"title": "", "abstract": ""}
        return cached_metadata[entry]


# This method only returns the ID, source code, entity_kname and the metadata for a given Solr document.
def relevant_doc_keys(solr_document, config):
    return {
        "id": solr_document["id"],
        "src": solr_document["src"],
        "entity_kname": solr_document.get("entity_kname", None),
        "metadata": get_entry_metadata(
            solr_document["session"], config
        ),  # Always load metadata to ensure cached document_index.json always contains it, regardless of config["add_metadata"]
    }


# This method fetches all documents, i.e. is any theorems, lemmas, corollaries and propositions
# from Solr in batches of 10000 documents per request.
def fetch_all_docs(solr, config):
    document_index = {}

    docs_per_page = 10000
    results = solr.search(
        config["solr_query"],
        start=0,
        rows=docs_per_page,
    )
    # Because the first response contains the total number of documents, that we need to determine the amount of pages that will be loaded,
    # solr.search() has to be called once before the for loop, and then within the for loop for each following page.
    max_docs = results.raw_response["response"]["numFound"]

    for result in results:
        result_filtered = relevant_doc_keys(result, config)
        document_index[result["id"]] = result_filtered

    pages = math.ceil(max_docs / docs_per_page) if docs_per_page > 0 else 1
    for i in range(1, pages):
        print(f"Fetching page {i + 1} of {pages} pages...")
        results = solr.search(
            config["solr_query"],
            start=i * docs_per_page,
            rows=docs_per_page,
        )

        for result in results:
            result_filtered = relevant_doc_keys(result, config)
            document_index[result["id"]] = result_filtered

    return document_index


# This method returns only relevant information from a given entry metadata (i.e. title, abstract, etc.).
# It removes newlines, short words, non-alphabetic characters, multiple or trailing whitespaces and stop words.
# This is done to decrease the amount of tokens required per informalized theorem.
def prepare_metadata(metadata, stop_words_set):
    # Replace newlines through spaces
    plain_text = metadata.lower().replace("\n", " ")

    # Replace 1-3 letter words and non-alphabetic characters with a single whitespace
    plain_text = re.sub(r"\b[a-z]{1,3}\b|[^a-z ]", " ", plain_text)

    # Replace two or more white spaces through single whitespace
    plain_text = re.sub(r"\s+", " ", plain_text).strip()

    # Remove stop words like e.g. "the", "a", "and", etc.
    plain_text_tokens = plain_text.split()
    tokens_without_stopwords = [
        word for word in plain_text_tokens if word not in stop_words_set
    ]

    plain_text = " ".join(tokens_without_stopwords)
    return plain_text


# This document generates document descriptions. That means that a LLM summaries each theorem into natural language.
# This process is only done for theorems that haven't been summarized or whose source code has changed.
# Source code changes are detected by calculating, saving and comparing the Adler32 checksum for a theorem's source code.
# Document summaries are generated by the configured LLM backend (Ollama or llama.cpp) through its local HTTP API.
# Generated document descriptions will be saved to the artifacts folder, configured at config["artifacts_folder"].
def generate_document_descriptions(
    config, document_index, prompts, tokenizer, save_every=1000
):
    ARTIFACTS_FOLDER = config["artifacts_folder"]
    DOCUMENT_DESCRIPTIONS = ARTIFACTS_FOLDER + "/" + "document_descriptions.json"

    if os.path.isfile(DOCUMENT_DESCRIPTIONS):
        print(f"Artifact {DOCUMENT_DESCRIPTIONS} already exists. Loading...")

        with open(DOCUMENT_DESCRIPTIONS, "r") as file:
            data = file.read()

        document_descriptions = json.loads(data)
        print(f"Finished loading {DOCUMENT_DESCRIPTIONS}")
    else:
        print(f"{DOCUMENT_DESCRIPTIONS} does not already exist.")
        document_descriptions = {}

    print("Finding documents that need to be described by the LLM...")

    filtered_docs = []
    # For each document in the document_index, calculate its Adler32 checksum, to determine whether it was changed.
    # All documents that need to be described by the LLM will be appended to filtered_docs.
    for doc_id in tqdm(document_index):
        doc = document_index[doc_id]
        checksum = zlib.adler32(doc["src"].encode("utf-8"))

        if doc["id"] not in document_descriptions:
            filtered_docs.append(doc)
        elif doc["id"] in document_descriptions:
            saved_checksum = document_descriptions[doc["id"]].get(
                "zlib.adler32_checksum", ""
            )
            if saved_checksum != checksum:
                print(
                    "Document identified by id '"
                    + doc["id"]
                    + "' already exists in document descriptions ("
                    + str(saved_checksum)
                    + ") but doesn't match current zlib.adler32 checksum ("
                    + str(checksum)
                    + "). This can happen if the theorem source code has changed. Adding to batch..."
                )
                filtered_docs.append(doc)

    print(
        "Found "
        + str(len(filtered_docs))
        + " documents that need to be described by the LLM."
    )

    if len(filtered_docs) >= 1:
        # Only update NLTK resources if any documents need to be described, to avoid unnecessary downloads
        print("Downloading/Updating NLTK resources (punkt and stopwords)...")
        nltk.download("punkt")
        nltk.download("stopwords")
        stop_words_set = set(stopwords.words("english"))

        doc_strings = []
        # Create all doc_strings, i.e. all prompts that contain the theorems and metadata, if enabled, along with the instructions for the LLM
        for doc in tqdm(filtered_docs):
            # Remove the proof part of the theorem source code, truncate to max length and strip trailing whitespaces
            theorem_content = (
                doc["src"].split("proof")[0][: config["theorem_max_length"]].strip()
            )

            # If enabled, add the metadata to the prompt, otherwise only provive the theorem content.
            if config["add_metadata"]:
                title = prepare_metadata(
                    doc["metadata"].get("title", ""), stop_words_set
                )
                abstract = prepare_metadata(
                    doc["metadata"].get("abstract", ""), stop_words_set
                )

                if len(title + abstract) > config["metadata_max_length"]:
                    abstract = (
                        abstract[: config["metadata_max_length"] - len(title) - 3]
                        + "..."
                    )

                if title == "":
                    title = "-- no title --"
                if abstract == "":
                    abstract = "-- no abstract --"

                doc_string = prompts["describe"].format(
                    theorem_content=theorem_content, title=title, abstract=abstract
                )
            else:
                doc_string = prompts["describe"].format(theorem_content=theorem_content)

            doc_strings.append(doc_string)

        print(
            "Calculating maximum number of tokens required to describe filtered documents..."
        )
        max_tokens = 0

        for doc in tqdm(doc_strings):
            token_ids = tokenizer.encode(doc)
            num_tokens = len(token_ids)

            if num_tokens > max_tokens:
                max_tokens = num_tokens

        print("Max tokens for prompt and document string: " + str(max_tokens))

        print("Loading LLM...")
        llm = get_document_llm(config)

        # Generate document descriptions for all filtered_docs
        for i in tqdm(range(0, len(filtered_docs), save_every)):
            print(
                "Document descriptions from index "
                + str(i)
                + " to "
                + str(i + save_every)
                + " of "
                + str(len(filtered_docs))
                + " documents with maximum batch size "
                + str(save_every)
                + "..."
            )
            batch_doc_strings = doc_strings[i : i + save_every]
            for j, doc_string in enumerate(tqdm(batch_doc_strings)):
                doc_id = filtered_docs[i + j]["id"]
                doc_src = filtered_docs[i + j]["src"]
                raw_llm_description = llm.generate(doc_string).strip()

                # For debugging purposes, only print the first the generated document descriptions
                if j < 3:
                    print(
                        f"Raw LLM output for doc_id {doc_id}: '{raw_llm_description}'"
                    )

                document_descriptions[doc_id] = {
                    "llm_description": raw_llm_description,
                    "zlib.adler32_checksum": zlib.adler32(doc_src.encode("utf-8")),
                    "model": document_model_name(config),
                    "prompt": doc_string,
                }

            print("Saving document descriptions to " + DOCUMENT_DESCRIPTIONS + "...")
            if not os.path.exists(ARTIFACTS_FOLDER):
                os.makedirs(ARTIFACTS_FOLDER)

            with open(DOCUMENT_DESCRIPTIONS, "w") as outfile:
                json.dump(document_descriptions, outfile, indent=4)

        print("Finished generating document descriptions.")
    else:
        print("No documents need to be described by the LLM.")

    return document_descriptions


# This method loads already generated document descriptions from the artifacts folder, configured at config["artifacts_folder"].
# It then extracts the content within the <BEGIN> and <END> parts. If extracting the content fails, we simply take the entire LLM output as is.
def get_document_descriptions(config, document_index, prompts, tokenizer):
    document_descriptions = generate_document_descriptions(
        config, document_index, prompts, tokenizer
    )

    print("Parsing LLM descriptions...")
    parsing_failed = 0

    for doc_id in tqdm(document_descriptions):
        try:
            llm_description = document_descriptions[doc_id]["llm_description"].split(
                "<BEGIN>"
            )[1]
        except Exception:
            parsing_failed += 1
            llm_description = document_descriptions[doc_id]["llm_description"]

        if doc_id in document_index:
            document_index[doc_id]["llm_description"] = llm_description

    if parsing_failed > 0:
        print(
            f"Warning: Could not extract theorem description using <BEGIN> and <END> from source provided by LLM for {parsing_failed} documents, thus loading them as-is."
        )

    return document_index


# Building the document index means, saving all loaded documents with its loaded entry metadata.
# This is done to avoid having to refetch all documents from Solr on every program start.
def build_document_index(config, solr):
    CACHE_FOLDER = config["cache_folder"]
    DOCUMENT_INDEX_CACHE = f"{CACHE_FOLDER}/document_index.json"

    if os.path.isfile(DOCUMENT_INDEX_CACHE):
        print(f"Cached {DOCUMENT_INDEX_CACHE} already exists. Loading...")

        with open(DOCUMENT_INDEX_CACHE, "r") as file:
            data = file.read()

        document_index = json.loads(data)
        print(f"Finished loading {DOCUMENT_INDEX_CACHE}")
    else:
        print(
            f"{DOCUMENT_INDEX_CACHE} does not already exist. Fetching all documents..."
        )
        document_index = fetch_all_docs(solr, config)

        # Double check in case that the .cache folder already exists, but the entry_db_cache.json does not exist
        if not os.path.exists(CACHE_FOLDER):
            os.makedirs(CACHE_FOLDER)

        with open(DOCUMENT_INDEX_CACHE, "w") as file:
            json.dump(document_index, file)

    return document_index
