from sentence_transformers import SentenceTransformer, CrossEncoder, util
from src.solr import docs_by_ids
from src.llm import save_llm_output_cache

import torch
import os
import time

def encode_embeddings(config, documents_tree, bi_encoder):
    CACHE_FOLDER = config["cache_folder"]
    EMBEDDINGS_CACHE = f"{CACHE_FOLDER}/embeddings_cache.pt"

    # Retrieve and Rerank pipeline
    if not torch.cuda.is_available():
        print("No GPU found, so the CPU will be used instead which may increase encoding and search duration.")

    if os.path.exists(EMBEDDINGS_CACHE):
        encoded_embeddings = torch.load(EMBEDDINGS_CACHE)
        print("Finished loading cached embeddings.")
    else:
        encoded_embeddings = bi_encoder.encode(
            documents_tree["documents"],
            convert_to_tensor=True,
            show_progress_bar=True)

        # Double check in case that the .cache folder already exists, but the entry_db_cache.json does not exist
        if not os.path.exists(CACHE_FOLDER):
            os.makedirs(CACHE_FOLDER)

        torch.save(encoded_embeddings, EMBEDDINGS_CACHE)

    return encoded_embeddings

def search(search_query, collection, prompts, generation_args, pipe, config, llm_output_cache=None):
    start = time.time()
    cached_duration = None
    docs_to_retrieve = 100
    llm_prompt = prompts["search_refine"].format(search_query=search_query)

    # TODO: Move this to a separate function
    if llm_output_cache is not None and config["llm_name"] in llm_output_cache and llm_prompt in llm_output_cache[config["llm_name"]]:
        print(f"Using cached LLM response for prompt '{llm_prompt[:200]}...'")
        refined_query = llm_output_cache[config["llm_name"]][llm_prompt]["output"]
        cached_duration = llm_output_cache[config["llm_name"]][llm_prompt]["output_duration"]
    else:
        output = pipe(llm_prompt, **generation_args)
        refined_query = output[0]['generated_text']

        end = time.time()
        output_duration  = end - start

        if config["llm_name"] not in llm_output_cache:
            llm_output_cache[config["llm_name"]] = {}

        llm_output_cache[config["llm_name"]][llm_prompt] = {
            "output": refined_query,
            "output_duration": output_duration
        }

        if config["enable_llm_output_cache"]:
            save_llm_output_cache(llm_output_cache, config)

    try:
        refined_query = refined_query.split("<BEGIN>")[1]
        refined_query = refined_query.split("<END>")[0]
    except Exception as err:
        print(f"Warning: Could not extract refined query using <BEGIN> and <END> from text generated by LLM for query '" + search_query + "', thus using it for search as is.")

    query_text = prompts["retrieve"].format(search_query=refined_query)
    query_result = collection.query(
        query_texts=[query_text],
        n_results=docs_to_retrieve
    )
    results = {}

    for metadata, distance in zip(query_result["metadatas"][0], query_result["distances"][0]):
        result_id = metadata["source"]
        results[result_id] = {
            "score": distance,
            "id": result_id
        }

    end = time.time()
    search_duration = end - start

    if cached_duration != None:
        search_duration = search_duration + cached_duration

    return {
        "results": results,
        "duration": search_duration,
        "refined_query": query_text
    }

# TODO: Fetch documents from Solr instead of document_tree
def search_results_to_docs(search_results, document_tree):
    for result_id in search_results["results"]:
        search_results["results"][result_id] = {
            **search_results["results"][result_id],
            **document_tree[result_id]
        }

    # Convert search_results["results"] to a list => this makes sorting or receiving the nth result easier
    search_results["results"] = [value for _, value in search_results["results"].items()]
    return search_results
